<div class="row m-0 justify-content-sm-center">
    <div class="col p-0">
        <img src="./DummyCategorie/boar.jpg" style="max-width: 100%;">
    </div>
    <div class="col p-0">
        <img src="./DummyCategorie/cat.jpg" style="max-width: 100%;">
    </div>
</div>
<div class="row m-0 justify-content-sm-center">
    <div class="col p-0">
        <img src="./DummyCategorie/donkey.jpg" style="max-width: 100%;">
    </div>
    <div class="col p-0">
        <img src="./DummyCategorie/duck.jpg" style="max-width: 100%;">
    </div>
</div>
