<div class="container mt-5">
    <div class="position-relative">
        <div id="subjectName">
            <span id="subjectNameText">Ente</span>
        </div>
        <div class="row justify-content-sm-center">
            <div class="col-lg-4 col-sm-6 imageContainer" id="container1">
                <img class="gameImage" src="./DummyCategorie/boar.jpg" id="boar">
                <span class="overlayPlaceholder"></span>
            </div>
            <div class="col-lg-4 col-sm-6 mt-sm-0 mt-3 imageContainer" id="container2">
                <img class="gameImage" src="./DummyCategorie/cat.jpg" id="cat">
                <span class="overlayPlaceholder"></span>
            </div>
        </div>
        <div class="row justify-content-sm-center">
            <div class="col-lg-4 col-sm-6 mt-sm-4 mt-3 imageContainer" id="container3">
                <img class="gameImage" src="./DummyCategorie/donkey.jpg" id="donkey">
                <span class="overlayPlaceholder"></span>
            </div>
            <div class="col-lg-4 col-sm-6 mt-sm-4 mt-3 imageContainer" id="container4">
                <img class="gameImage" src="./DummyCategorie/duck.jpg" id="duck">
                <span class="overlayPlaceholder"></span>
            </div>
        </div>
    </div>
</div>
