<div class="container mt-5">
    <div class="row">
        <div class="col">
            <label for="name">Kategorie</label>
            <input type="text" class="form-control" id="name" placeholder="Name eingeben" value="Tiere">
        </div>
        <div class="col">
            <button type="button" class="btn btn-danger deleteButton float-right"
                    style="border-radius: 50%; background: #DC3545; width: 60px; height:60px;" data-toggle="modal"
                    data-target="#deleteCategorie">
                <img src="./DummyCategorie/delete-forever.svg" style="width: 100%; height:100%; position: center;">
            </button>
        </div>
    </div>

    <div class="card-deck mt-4">

        <?php
        $map = array(
            array('cat', 'Katze'),
            array('boar', 'Wildschwein'),
            array('chicken', 'Huhn'),
            array('cow', 'Kuh'),
            array('dog', 'Hund'),
            array('donkey', 'Esel'),
        );
        foreach ($map as $entry) { ?>
            <div class="card imageCard">
                <label for="file" class="customFile">
                    <input type="file" id="file" name="file">
                    <img src="./DummyCategorie/<?= $entry[0] ?>.jpg" class="card-img-top editImage"
                         style="position: relative;">
                </label>

                <button type="button" class="btn btn-danger deleteButton"
                        style="border-radius: 50%; position: absolute; right: 2px; top: 2px; background: #DC3545 url('./DummyCategorie/delete.svg')no-repeat center; width: 30px; height:30px;">
                </button>
                <div class="card-body">
                    <input type="text" class="form-control" id="password" value="<?= $entry[1] ?>">
                </div>
            </div>
        <?php } ?>
    </div>

    <div class="card-deck mt-4">
        <?php
        $map = array(
            array('duck', 'Ente'),
            array('horse', 'Pferd'),
            array('monkey', 'Affe'),
            array('pig', 'Schwein'),
            array('turkey', 'Truthahn'),
        );
        foreach ($map as $entry) { ?>
            <div class="card imageCard">
                <label for="file" class="customFile">
                    <input type="file" id="file" name="file">
                    <img src="./DummyCategorie/<?= $entry[0] ?>.jpg" class="card-img-top editImage"
                         style="position: relative;">
                </label>

                <button type="button" class="btn btn-danger deleteButton"
                        style="border-radius: 50%; position: absolute; right: 2px; top: 2px; background: #DC3545 url('./DummyCategorie/delete.svg')no-repeat center; width: 30px; height:30px;">
                </button>
                <div class="card-body">
                    <input type="text" class="form-control" id="password" value="<?= $entry[1] ?>">
                </div>
            </div>
        <?php } ?>
        <div class="card imageCard">
            <label for="file" class="customFile">
                <input type="file" id="file" name="file">
                <img src="./DummyCategorie/addImage.png" class="card-img-top editImage" style="position: relative;">
            </label>
            <div class="card-body">
                <input type="text" class="form-control" placeholder="Name eingeben">
            </div>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col">
            <button type="button" class="btn btn-secondary mb-3" data-toggle="modal" data-target="#discardChanges">
                verwerfen
            </button>
        </div>
        <div class="col">
            <a href="?site=category-view" class="btn btn-primary mb-3 float-right">
                speichern
            </a>
        </div>
    </div>


    <div class="modal fade" id="discardChanges" tabindex="-1" role="dialog" aria-labelledby="modalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalLabel">Änderungen verwerfen ?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">abbrechen</button>
                    <a href="/" class="btn btn-danger">bestätigen</a>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="deleteCategorie" tabindex="-1" role="dialog" aria-labelledby="modalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalLabel">Kategorie wirklich löschen?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">abbrechen</button>
                    <a href="/" class="btn btn-danger">bestätigen</a>
                </div>
            </div>
        </div>
    </div>
</div>
