<div class="container mt-5">
    <div class="row">
    <div class="col">
        <label for="name">Kategorie</label>
        <input type="text" class="form-control" id="name" placeholder="Name eingeben">
    </div>
    <div class="col">
        &nbsp;
    </div>
</div>
<div class="card imageCard mt-4" style="width: 8vw">
    <label for="file" class="customFile">
        <input type="file" id="file" name="file">
        <img src="./DummyCategorie/addImage.png" class="card-img-top editImage" style="position: relative;">
    </label>
    <div class="card-body">
        <input type="text" class="form-control" placeholder="Name eingeben">
    </div>
</div>

<div class="row mt-5">
    <div class="col">
        <button type="button" class="btn btn-secondary mb-3" data-toggle="modal" data-target="#discardChanges">
            verwerfen
        </button>
    </div>
    <div class="col">
        <a href="?site=category-view" class="btn btn-primary mb-3 float-right">
            speichern
        </a>
    </div>
</div>


<div class="modal fade" id="discardChanges" tabindex="-1" role="dialog" aria-labelledby="modalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel">Änderungen verwerfen ?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">abbrechen</button>
                <a href="/" class="btn btn-danger">bestätigen</a>
            </div>
        </div>
    </div>
</div>
</div>
