<div class="container mt-5">
    <div class="form-group">
        <div class="row">
            <div class="col">
                <label for="name">Vorname</label>
                <input type="text" class="form-control" id="name" placeholder="Vorname" value="Manuel">
            </div>
            <div class="col">
                <label for="surename">Nachname</label>
                <input type="text" class="form-control" id="surename" placeholder="Nachname" value="Adams">
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="email">E-Mail-Adresse</label>
        <input type="email" class="form-control" id="email" placeholder="E-Mail-Adresse" value="Adams.Manuel@gmail.com">
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" placeholder="*******" value="">
            </div>
            <div class="col">
                <label for="verifyPassword">Passwort bestaetigen</label>
                <input type="password" class="form-control" id="verifyPassword" placeholder="*******" value="">
            </div>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col">
            <button type="button" class="btn btn-secondary mb-3" data-toggle="modal" data-target="#discardChanges">
                verwerfen
            </button>
        </div>
        <div class="col">
            <a href="/" class="btn btn-primary mb-3 float-right">
                speichern
            </a>
        </div>
    </div>


    <div class="modal fade" id="discardChanges" tabindex="-1" role="dialog" aria-labelledby="modalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalLabel">Änderungen verwerfen ?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">abbrechen</button>
                    <a href="/" class="btn btn-danger">bestätigen</a>
                </div>
            </div>
        </div>
    </div>
</div>
