<div class="container mt-5">
    <div class="form-group">
        <label for="email">E-Mail-Adresse</label>
        <input type="email" class="form-control" id="email" placeholder="E-Mail-Adresse eingeben">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" placeholder="Password eingeben">
    </div>
    <div class="row mt-5">
        <div class="col">
            <a href="?site=user-create" class="btn btn-secondary mb-3">
                Konto erstellen
            </a>
        </div>
        <div class="col">
            <a href="/" class="btn btn-primary mb-3 float-right">
                Anmelden
            </a>
        </div>
    </div>
</div>
