<div class="container mt-5">
    <div class="form-group">
        <label for="email">E-Mail-Adresse</label>
        <input type="email" class="form-control" id="email" placeholder="E-Mail-Adresse eingeben"
               value="manuel.adams@hs-weingarten.de">
    </div>
    <div class="form-group">
        <label for="verifyCode">Bitte geben sie den Verifizierungs-code ein</label>
        <input type="email" class="form-control" id="verifyCode" placeholder="Verifizierungs-code">
    </div>
    <div class="row mt-5">
        <div class="col">
            <a href="?site=user-create" class="btn btn-secondary mb-3">
                zurück
            </a>
        </div>
        <div class="col">
            <a href="/" class="btn btn-primary mb-3 float-right">
                bestätigen
            </a>
        </div>
    </div>
</div>
