<div class="container mt-5">
    <form>
        <div class="form-group">
            <div class="row">
                <div class="col">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" placeholder="Vorname eingeben">
                </div>
                <div class="col">
                    <label for="surename">&nbsp;</label>
                    <input type="text" class="form-control" id="surename" placeholder="Nachname eingeben">
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="email">E-Mail-Adresse</label>
            <input type="email" class="form-control" id="email" placeholder="E-Mail-Adresse eingeben">
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" placeholder="Password eingeben">
                </div>
                <div class="col">
                    <label for="verifyPassword">Passwort bestätigen</label>
                    <input type="password" class="form-control" id="verifyPassword" placeholder="bestätigen">
                </div>
            </div>

        </div>
        <div class="row mt-5">
            <div class="col">
                <a href="?site=user-login" class="btn btn-secondary mb-3">
                    Stattdessen anmelden
                </a>
            </div>
            <div class="col">
                <a href="?site=user-verify-email" class="btn btn-primary mb-3 float-right">
                    weiter
                </a>
            </div>
        </div>
    </form>
</div>
